# Jekyll Configuration for Impact Evaluator Research
title: "MERIter Modelling"
description: "Aligning work on MERIters via semi-formal models and maps"
author: "Adam Spiers"
baseurl: ""
url: ""

# Build settings
markdown: kramdown
highlighter: rouge
# Plugins
plugins:
  - jekyll-asciidoc
  - jekyll-feed
  - jekyll-sitemap

# AsciiDoc configuration
asciidoc:
  processor: asciidoctor
  ext: asciidoc,adoc,ad

asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=rouge
    - icons=font
    - experimental=true
    - toc=left
    - toclevels=3

# Collection settings
collections:
  chapters:
    output: true
    permalink: /:collection/:name/
    sort_by: order
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# Pagination (disabled for research site)
# paginate: 10
# paginate_path: /page:num/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "chapters"
    values:
      layout: "chapter"
      author: "IE Research Team"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "single"
      author: "IE Research Team"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"

# PDF generation settings
pdf:
  title: "Generalized Impact Evaluators: Model and Visualization"
  author: "IE Research Team"
  subject: "Impact Evaluator Research"
  keywords: "impact evaluation, abstract models, visualization, composability"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .sass-cache
  - _site
  - "*.puml"
  - Makefile
  - .git
  - .gitignore
  - AGENTS.md
  - CLAUDE.md
  - tmp/
  - .ai/

# Good f'in luck if you want to ignore emacs temp/lock files :-(
# Neither of these work ... at all.
# https://github.com/jekyll/jekyll-watch/pull/91
# https://github.com/jekyll/jekyll-watch/pull/93
