@startuml "Impact Evaluator ERD"
title "Impact Evaluator ERD"

'skinparam linetype ortho

package "IE Governance (meta)" as IEGovernance {
    entity ObjectivesDesigner
    entity ScopesDesigner
    entity MeasurementDesigner
    entity EvaluationDesigner
    entity RewardDesigner
    entity Treasury

    ScopesDesigner -r[hidden]-> MeasurementDesigner
    MeasurementDesigner -r[hidden]-> EvaluationDesigner
    EvaluationDesigner -r[hidden]-> RewardDesigner
    RewardDesigner -r[hidden]-> Treasury

    ObjectivesDesigner "1" --> "1" ScopesDesigner : orients
    ObjectivesDesigner "1" --> "1" MeasurementDesigner : orients
    ObjectivesDesigner "1" --> "1" EvaluationDesigner : orients
    ObjectivesDesigner "1" --> "1" RewardDesigner : orients
}

package Impact {
    entity ImpactOrganization
    entity ImpactProject {
        organization
    }
    entity ImpactWork
    dataclass ImpactScope {
        project
        epoch or timeInterval
    }
    dataclass ImpactClaim {
        scope
        timeInterval
        extra data
    }
    note left of ImpactClaim
        Vehicle for ImpactContributor
        entities to communicate
        outcomes to Measurers
    end note
    entity ImpactContributor

    ImpactOrganization "1" -d-> "*" ImpactProject : facilitates
    ImpactProject "1" -d-> "*" ImpactScope : divides\ninto
    ImpactScope "1" -d-> "*" ImpactClaim : contains
    ImpactContributor "*" -u-> "*" ImpactClaim : claims
    ImpactContributor "*" --> "*" ImpactWork : > contributes
    ImpactContributor "1" --> "1" ImpactWorkPolicy : decides
    ImpactWorkPolicy "1" -u-> "*" ImpactWork : > influences
    ImpactClaim "*" --> "*" ImpactWork : > represents
    ImpactContributor "1" -up-> "1" ImpactOrganization : > belongs to
}

package Measure {
    dataclass Measurement {
        indicator
        timeInterval
        entity
    }
    entity Measurer

    ImpactClaim "*" --> "*" Measurer : "submitted to\n(or discovered by)    "

    Measurer "1" --> "*" Measurement : takes
    Measurement "*" -l-> "1" ImpactClaim : measures
    Measurement::entity "1" --> "1" ImpactContributor : credits
}

package Evaluate {
    dataclass EvaluationResult {
        timestamp
    }
    entity Evaluator

    EvaluationResult "1" -l-> "*" Measurement : evaluates
    Evaluator "1" -d-> "*" EvaluationResult : "calculates    "
    EvaluationResult "*" -u-> "*" Evaluator : "cascaded\nto"
}

package Reward {
    entity RewardCalculator
    dataclass RewardAllocation {
        amount
        recipient
        impactClaimId
    }
    entity RewardDistributor

    RewardCalculator "1" -d-> "*" RewardAllocation : calculates
    RewardAllocation "*" -r-> "1" RewardDistributor : authorizes
}

Impact -r[hidden]--> Measure
Measure -r[hidden]--> Evaluate
Evaluate -r[hidden]--> Reward

ScopesDesigner "1" --> "*" ImpactScope : designs
MeasurementDesigner "1" --> "*" Measurer : designs
EvaluationDesigner "1" --> "*" Evaluator : designs
RewardDesigner "1" --> "1" RewardCalculator : designs

entity FundingSource
FundingSource "*" --> "1" Treasury : funds
Treasury "1" --> "1" RewardDistributor : funds

Measurement "*" --> "*" Evaluator : "ingested     \nby     "
EvaluationResult "1" --> "1" RewardCalculator : steers >
RewardDistributor "1" -d-> "*" ImpactContributor : > rewards
RewardDistributor "1" -d-> "*" ImpactWorkPolicy : > influences

ExternalMarket "1" -u-> "*" RewardAllocation : values

@enduml
