@startuml "Impact Evaluator ERD"
title "Impact Evaluator ERD"

'skinparam linetype ortho

package "IE Governance (meta)" as IEGovernance {
    class ObjectivesDesigner {}
    class ScopesDesigner {}
    class MeasurementDesigner {}
    class EvaluationDesigner {}
    class RewardDesigner {}
    class Treasury {}

    ObjectivesDesigner -d[hidden]-> ScopesDesigner
    ScopesDesigner -r[hidden]-> MeasurementDesigner
    MeasurementDesigner -r[hidden]-> EvaluationDesigner
    EvaluationDesigner -r[hidden]-> RewardDesigner
    RewardDesigner -r[hidden]-> Treasury

    ObjectivesDesigner --> ScopesDesigner : orients
    ObjectivesDesigner --> MeasurementDesigner : orients
    ObjectivesDesigner --> EvaluationDesigner : orients
    ObjectivesDesigner --> RewardDesigner : orients
}

package Impact {
    class ImpactOrganization {
        identity
    }
    class ImpactProject {
        organization
    }
    class ImpactScope {
        project
        epoch or timeInterval
    }
    class ImpactClaim {
        scope
        timeInterval
        extra data
    }
    note left of ImpactClaim
        Vehicle for ImpactContributor
        entities to communicate
        outcomes to Measurers
    end note
    class ImpactContributor {
        identity
    }

    ImpactOrganization "1" -d-> "*" ImpactProject : facilitates
    ImpactProject "1" -d-> "*" ImpactScope : divides\ninto
    ImpactScope "1" -d-> "*" ImpactClaim : contains
    ImpactContributor "1" -u-> "*" ImpactClaim : claims
}

package Measure {
    class Measurement {
        indicator
        entity
        timeInterval
    }
    class Measurer {
        identity
    }

    ' This screws up the layout for some reason:
    'ImpactClaim --> Measurer : submitted to

    Measurer "1" --> "*" Measurement : takes
    Measurement "*" -l-> "1" ImpactClaim : measured by
    Measurement::entity "1" --> "1" ImpactContributor : credits
}

package Evaluate {
    class Evaluation {
        timestamp
    }
    class Evaluator {
        identity
    }

    Evaluator "1" -d-> "*" Evaluation : performs
    Evaluation "1" -l-> "*" Measurement : evaluates
    Evaluation --> Evaluation : "\n> depends on"
}

package Reward {
    class RewardCalculator {}
    class RewardAllocation {}

    RewardCalculator "1" --> "*" RewardAllocation : calculates
}

Impact -r[hidden]--> Measure
Evaluate -r[hidden]--> Reward
Measurement -r[hidden]--> Evaluation
Evaluation -r[hidden]--> RewardCalculator

ScopesDesigner "1" --> "*" ImpactScope : designs
MeasurementDesigner "1" --> "*" Measurer : designs
EvaluationDesigner "1" --> "*" Evaluator : designs
RewardDesigner "1" --> "*" RewardCalculator : designs

Treasury -r--> RewardAllocation : funds

Evaluation "1" -r-> "*" RewardCalculator : steers >
RewardAllocation "1" --[norank]-> "*" ImpactContributor : rewards

FundingSource "*" -d-> "1" Treasury : funds

@enduml
