---
layout: chapter
---

= MERIter Research

This site relates to a relatively new field of research on a common
pattern of system design which iteratively incentivizes impact
projects through a repeated loop of Monitoring, Evaluation, and
Rewards of Impact ("MERI").  It builds on the
https://research.protocol.ai/publications/generalized-impact-evaluators/[Protocol
Labs whitepaper^] on Generalized Impact Evaluators, or IEs for short.
Alternative names are currently being considered, including "MERIters"
and "MER-loops".

The applicability of this design pattern spans a huge diversity of industries,
methodologies, and theoretical frameworks.

[NOTE]
====
For a presentation of this work, see: https://docs.google.com/presentation/d/14MPNwTc6fiNWDA1AL22YNVaWUjbF9n5aOgt4DGjUPFY/edit?usp=sharing[MERIters Presentation^]
====

== Overview

This research explores modularity, data and process models, and
visualizations, as approaches for coordinating work in this space.

image::diagrams/ERD.svg[ERD Diagram,align="center",link=diagrams/ERD.svg]

The diagram shows the conceptual model for Impact Evaluator systems
with entities grouped into logical packages:

* Impact
* Measurement
* Evaluation
* Rewards
* Governance
