---
title: "Impact Claims"
excerpt: "Self-reported impact claims as foundational data structures"
slug: "impact-claims"
chapter_number: 3
order: 3
date: 2025-08-06
layout: chapter
---

= Impact Claims

While impact claims are clearly at the heart of Hypercerts, independent measurements and evaluations are also effectively claims relating to those impact claims.  Furthermore, impact claims are not made in a vacuum, but within the context of specific scopes and methodologies.  For example, an impact claim contains an implicit eligibility claim that the claimant is a valid participant of the relevant project or scope, and therefore eligible for making that impact claim.  The impact claim is also typically made according to a specific methodology or theory of change, for which there is a claim of validity: if claims that the methodology is sound are proven to be invalid, then any impact claim based on that methodology lose credibility.  Further claims could be made on the authorship of the methodology, on reviews of its validity, on reviews and/or endorsements of those reviews, and so on, potentially ad infinitum.

This line of thinking leads to the conclusion that a directed graph of claims is required, facilitating creation and verification of chains of claims.  And allowing all of these claims to be made permissionlessly allows webs of trust to emerge organically which all lend credibility to the original impact claim under scrutiny.

When claims are made in a structured way in public, they are effectively attestations.  Fortunately there already exists very nice infrastructure for constructing onchain and offchain attestations, in the form of EAS (Ethereum Attestation Service).


TODO:

Include this relevant quote from https://www.hypercerts.org/docs/whitepaper/hypercerts-intro#examples:

The key point is the

> Importantly a hypercert does not specify the “size” of the impact, e.g. a hypercert does not state “5 tons of CO2 removed from the atmosphere.” Instead the hypercert only defines the work, e.g. “200 trees protected” (scope of work) in 2022 (time of work). The size of the impact is then left to the evaluations of the “CO2 in the atmosphere” (scope of impact) in 2022 (time of impact) that point towards the covered region of the hypercert. For instance: This allows a self evaluation to claim that 5 tons of CO2 were removed in a given year as well as one or multiple evaluations from independent auditors to confirm or challenge how much CO2 has been removed. An evaluator could detect that some of the trees were not healthy and hence only 4 tons of CO2 were removed. Allowing for multiple evaluation is a defining characteristic of the open evaluation system.


https://www.hypercerts.org/docs/developer/metadata#example-3-hypercert-with-excluded-impact-claims

https://github.com/hypercerts-org/ecocerts/issues/3
